"""owner id for elections

Revision ID: a690068d28a7
Revises: f6cacfb3a950
Create Date: 2025-12-02 15:37:26.136850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a690068d28a7'
down_revision: Union[str, Sequence[str], None] = 'f6cacfb3a950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'elections',
        sa.Column('owner_id', sa.String(length=36), nullable=False),
    )
    op.create_foreign_key(
        'fk_elections_owner_id_users',
        'elections',
        'users',
        ['owner_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_elections_owner_id_users', 'elections', type_='foreignkey')
    op.drop_column('elections', 'owner_id')
    # ### end Alembic commands ###
