"""add_indexes_to_models

Revision ID: f6cacfb3a950
Revises: b3c7514ed434
Create Date: 2025-12-01 17:47:38.828957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cacfb3a950'
down_revision: Union[str, Sequence[str], None] = 'b3c7514ed434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_attachment_candidate_id', 'attachments', ['candidate_id'], unique=False)
    op.create_index('idx_attachment_election_id', 'attachments', ['election_id'], unique=False)
    op.create_index('idx_attachment_uploaded_at', 'attachments', ['uploaded_at'], unique=False)
    op.create_index('idx_attachment_user_id', 'attachments', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'attachments', ['id'])
    op.create_index('idx_audit_log_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_log_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'audit_logs', ['id'])
    op.create_index('idx_candidate_election_id', 'candidates', ['election_id'], unique=False)
    op.create_unique_constraint(None, 'candidates', ['id'])
    op.create_index('idx_election_access_election_id', 'election_access', ['election_id'], unique=False)
    op.create_index('idx_election_access_election_user', 'election_access', ['election_id', 'user_id'], unique=False)
    op.create_index('idx_election_access_user_id', 'election_access', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'election_access', ['id'])
    op.create_index('idx_election_results_cache_updated_at', 'election_results_cache', ['updated_at'], unique=False)
    op.create_unique_constraint(None, 'election_results_cache', ['id'])
    op.create_unique_constraint(None, 'election_settings', ['id'])
    op.create_index('idx_election_created_at', 'elections', ['created_at'], unique=False)
    op.create_index('idx_election_dates', 'elections', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_election_end_date', 'elections', ['end_date'], unique=False)
    op.create_index('idx_election_is_public', 'elections', ['is_public'], unique=False)
    op.create_index('idx_election_start_date', 'elections', ['start_date'], unique=False)
    op.create_unique_constraint(None, 'elections', ['id'])
    op.create_index('idx_login_attempt_email', 'login_attempts', ['email'], unique=False)
    op.create_index('idx_login_attempt_email_timestamp', 'login_attempts', ['email', 'timestamp'], unique=False)
    op.create_index('idx_login_attempt_success', 'login_attempts', ['success'], unique=False)
    op.create_index('idx_login_attempt_timestamp', 'login_attempts', ['timestamp'], unique=False)
    op.create_index('idx_login_attempt_user_id', 'login_attempts', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'login_attempts', ['id'])
    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notification_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.create_index('idx_password_reset_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'password_reset_tokens', ['id'])
    op.create_unique_constraint(None, 'user_profiles', ['id'])
    op.create_index('idx_user_role_link_role_id', 'user_role_links', ['role_id'], unique=False)
    op.create_index('idx_user_role_link_user_id', 'user_role_links', ['user_id'], unique=False)
    op.create_index('idx_user_role_link_user_role', 'user_role_links', ['user_id', 'role_id'], unique=False)
    op.create_unique_constraint(None, 'user_role_links', ['id'])
    op.create_unique_constraint(None, 'user_roles', ['id'])
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_index('idx_vote_log_timestamp', 'vote_logs', ['timestamp'], unique=False)
    op.create_index('idx_vote_log_vote_id', 'vote_logs', ['vote_id'], unique=False)
    op.create_unique_constraint(None, 'vote_logs', ['id'])
    op.create_index('idx_vote_candidate_id', 'votes', ['candidate_id'], unique=False)
    op.create_index('idx_vote_created_at', 'votes', ['created_at'], unique=False)
    op.create_index('idx_vote_election_id', 'votes', ['election_id'], unique=False)
    op.create_index('idx_vote_election_voter', 'votes', ['election_id', 'voter_id'], unique=False)
    op.create_index('idx_vote_voter_id', 'votes', ['voter_id'], unique=False)
    op.create_unique_constraint(None, 'votes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='unique')
    op.drop_index('idx_vote_voter_id', table_name='votes')
    op.drop_index('idx_vote_election_voter', table_name='votes')
    op.drop_index('idx_vote_election_id', table_name='votes')
    op.drop_index('idx_vote_created_at', table_name='votes')
    op.drop_index('idx_vote_candidate_id', table_name='votes')
    op.drop_constraint(None, 'vote_logs', type_='unique')
    op.drop_index('idx_vote_log_vote_id', table_name='vote_logs')
    op.drop_index('idx_vote_log_timestamp', table_name='vote_logs')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'user_role_links', type_='unique')
    op.drop_index('idx_user_role_link_user_role', table_name='user_role_links')
    op.drop_index('idx_user_role_link_user_id', table_name='user_role_links')
    op.drop_index('idx_user_role_link_role_id', table_name='user_role_links')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.drop_index('idx_password_reset_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_expires_at', table_name='password_reset_tokens')
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_index('idx_notification_user_read_created', table_name='notifications')
    op.drop_index('idx_notification_user_id', table_name='notifications')
    op.drop_index('idx_notification_is_read', table_name='notifications')
    op.drop_index('idx_notification_created_at', table_name='notifications')
    op.drop_constraint(None, 'login_attempts', type_='unique')
    op.drop_index('idx_login_attempt_user_id', table_name='login_attempts')
    op.drop_index('idx_login_attempt_timestamp', table_name='login_attempts')
    op.drop_index('idx_login_attempt_success', table_name='login_attempts')
    op.drop_index('idx_login_attempt_email_timestamp', table_name='login_attempts')
    op.drop_index('idx_login_attempt_email', table_name='login_attempts')
    op.drop_constraint(None, 'elections', type_='unique')
    op.drop_index('idx_election_start_date', table_name='elections')
    op.drop_index('idx_election_is_public', table_name='elections')
    op.drop_index('idx_election_end_date', table_name='elections')
    op.drop_index('idx_election_dates', table_name='elections')
    op.drop_index('idx_election_created_at', table_name='elections')
    op.drop_constraint(None, 'election_settings', type_='unique')
    op.drop_constraint(None, 'election_results_cache', type_='unique')
    op.drop_index('idx_election_results_cache_updated_at', table_name='election_results_cache')
    op.drop_constraint(None, 'election_access', type_='unique')
    op.drop_index('idx_election_access_user_id', table_name='election_access')
    op.drop_index('idx_election_access_election_user', table_name='election_access')
    op.drop_index('idx_election_access_election_id', table_name='election_access')
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_index('idx_candidate_election_id', table_name='candidates')
    op.drop_constraint(None, 'audit_logs', type_='unique')
    op.drop_index('idx_audit_log_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_log_entity', table_name='audit_logs')
    op.drop_index('idx_audit_log_action', table_name='audit_logs')
    op.drop_constraint(None, 'attachments', type_='unique')
    op.drop_index('idx_attachment_user_id', table_name='attachments')
    op.drop_index('idx_attachment_uploaded_at', table_name='attachments')
    op.drop_index('idx_attachment_election_id', table_name='attachments')
    op.drop_index('idx_attachment_candidate_id', table_name='attachments')
    # ### end Alembic commands ###
